CREATE TABLE items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  location TEXT,
  contact TEXT,
  date VARCHAR(50),
  claimcode TEXT,
  image TEXT,
  status TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  returned_at TIMESTAMPTZ
);

--  Sample data
INSERT INTO items (title, description, category, location, date, status, contact, claimcode, image, created_at) VALUES
('iPhone 15 Pro', 'Black iPhone 15 Pro with a blue case. Has a small scratch on the back.', 'Electronics', 'Student Center, Cafeteria', '2026-04-19', 'lost', 'john.doe@email.com', 'LF-4821', 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=400&q=80', NOW()),
('Brown Leather Wallet', 'Contains ID and credit cards. Brown leather bifold wallet.', 'Accessories', 'Library, 3rd Floor', '2026-04-17', 'lost', '+60 12-345 6789', 'LF-7703', 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&q=80', NOW()),
('Set of Keys', 'Keychain with car key and house keys. Blue rubber keychain.', 'Keys', 'Parking Lot B', '2026-04-19', 'lost', 'sarah.k@gmail.com', 'LF-1190', 'https://images.unsplash.com/photo-1605822105816-76b7cfd71142?w=400&q=80', NOW()),
('Prescription Glasses', 'Black frame glasses found in a blue case.', 'Accessories', 'Gym, Locker Room', '2026-04-19', 'found', 'mike.tan@uni.edu', 'LF-3356', 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=400&q=80', NOW()),
('Blue North Face Jacket', 'Size Medium blue puffer jacket.', 'Clothing', 'Building A, Room 201', '2026-04-18', 'found', '+60 16-999 0011', 'LF-6642', 'https://images.unsplash.com/photo-1497340525489-441e8427c980?w=400&q=80', NOW()),
('Student ID Card', 'Student ID card found near the entrance.', 'Documents', 'Main Entrance', '2026-04-20', 'found', 'reception@uni.edu', 'LF-2278', 'https://images.unsplash.com/photo-1668903678359-e810dd966016?w=400&q=80', NOW());